export REPLACERESOLVER_LOCATION="$1"

export PYTHONPATH=$REPLACERESOLVER_LOCATION/lib/python3.9/site-packages:$PYTHONPATH
export PXR_PLUGINPATH_NAME="$REPLACERESOLVER_LOCATION/plugin/usd:$PXR_PLUGINPATH_NAME"

